spring:
  application:
    name: project-mgt-service

server:
  port: 9020

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org.springframework.web: DEBUG